spring:
  application:
    name: jobapply-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/jobapply
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
